In [23]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.decomposition import PCA

%matplotlib inline

In [24]:
df = pd.read_csv("productDetailData.csv")
df.head()

,id,name,authors,original_price,price,categories,all_time_quantity_sold,rating_average,review_count,pages,manuafacture
0,74021317,Cây Cam Ngọt Của Tôi,José Mauro de Vasconcelos,108000,75500,Sách tiếng Việt,72808.0,5.0,13292,244.0,Nhà Xuất Bản Hội Nhà Văn
1,188940817,Vị Thần Của Những Quyết Định,Universe,79000,63000,Sách chiêm tinh - horoscope - khác,2.0,0.0,0,320.0,Nhà Xuất Bản Thế Giới
2,189643105,Không Phải Sói Nhưng Cũng Đừng Là Cừu -Tặng kè...,Lê Bảo Ngọc,128000,115000,Sách tư duy - Kỹ năng sống,NaN,0.0,0,296.0,Nhà Xuất Bản Thế Giới
3,26114399,"Nóng Giận Là Bản Năng , Tĩnh Lặng Là Bản Lĩnh",Tống Mặc,89000,50730,Sách tiếng Việt,74507.0,4.8,7206,264.0,Nhà Xuất Bản Thế Giới
4,109017985,"Thiên Tài Bên Trái, Kẻ Điên Bên Phải (Tái Bản)",Cao Minh,179000,116000,Truyện ngắn - Tản văn - Tạp Văn Nước Ngoài,25929.0,4.8,5429,424.0,Nhà Xuất Bản Thế Giới

In [25]:
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

In [26]:
df.drop("id", axis=1, inplace=True)

In [27]:
df1 = pd.get_dummies(df, columns=['name', 'authors', 'categories', 'manuafacture'])

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1393 entries, 0 to 1789
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    1393 non-null   object
 1   authors                 1393 non-null   object
 2   original_price          1393 non-null   int64
 3   price                   1393 non-null   int64
 4   categories              1393 non-null   object
 5   all_time_quantity_sold  1393 non-null   float64
 6   rating_average          1393 non-null   float64
 7   review_count            1393 non-null   int64
 8   pages                   1393 non-null   float64
 9   manuafacture            1393 non-null   object
dtypes: float64(3), int64(3), object(4)
memory usage: 119.7+ KB

In [29]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1393 entries, 0 to 1789
Columns: 2521 entries, original_price to manuafacture_ĐHQG Hà Nội
dtypes: bool(2515), float64(3), int64(3)
memory usage: 3.4 MB

In [30]:
pca = PCA(n_components=10)
df1_pca = pca.fit_transform(df1)

In [34]:
df1_pca = pd.DataFrame(df1_pca)
df1_pca.head()

,0,1,2,3,4,5,6,7,8,9
0,-57114.197713,69366.931069,262.550399,12275.198660,92.995312,0.625229,-0.753372,0.559841,0.056436,-0.104150
1,-87740.969754,-3779.034392,5475.550152,-338.808158,-70.471011,4.716724,-0.147350,-0.793593,0.333397,-0.042623
2,-87312.329269,71324.950643,-7575.184281,6169.067505,34.825288,0.511113,0.067556,-0.632151,0.272019,-0.151215
3,23768.937172,22821.042626,-13021.011013,4813.624230,-50.092258,0.366543,-0.722123,-0.713266,0.319594,-0.072573
4,-92499.072572,30547.160726,580.014627,5226.646824,50.401800,0.117698,-0.870543,0.273544,-0.069761,-0.110154